In [ ]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
input_size  =  9
hidden_size = 16
num_layers  =  1
actfun      = 'tanh'
bias        = True

rnn = nn.RNN(input_size,hidden_size,num_layers,nonlinearity=actfun,bias=bias)
print(rnn)

RNN(9, 16)


In [ ]:
seqlength = 5
batchsize = 2

X = torch.rand(seqlength,batchsize,input_size)

hidden = torch.zeros(num_layers,batchsize,hidden_size)

y,h = rnn(X,hidden)
print(f' Input shape: {list(X.shape)}')
print(f'Hidden shape: {list(h.shape)}')
print(f'Output shape: {list(y.shape)}')

 Input shape: [5, 2, 9]
Hidden shape: [1, 2, 16]
Output shape: [5, 2, 16]


In [ ]:
y,h1 = rnn(X,hidden)
print(h1), print('\n\n')

y,h2 = rnn(X)
print(h2), print('\n\n')

print(h1-h2)

tensor([[[ 0.1584, -0.0441,  0.0777,  0.5310,  0.2887, -0.0971,  0.3872,
          -0.6887, -0.5726, -0.2087, -0.3755, -0.2254, -0.2023, -0.6014,
           0.1702, -0.1733],
         [ 0.3551, -0.3533,  0.2359,  0.5652,  0.3833, -0.0084,  0.3274,
          -0.6864, -0.3683, -0.1570, -0.4752, -0.6122, -0.2165, -0.4626,
           0.1371,  0.1906]]], grad_fn=<StackBackward0>)



tensor([[[ 0.1584, -0.0441,  0.0777,  0.5310,  0.2887, -0.0971,  0.3872,
          -0.6887, -0.5726, -0.2087, -0.3755, -0.2254, -0.2023, -0.6014,
           0.1702, -0.1733],
         [ 0.3551, -0.3533,  0.2359,  0.5652,  0.3833, -0.0084,  0.3274,
          -0.6864, -0.3683, -0.1570, -0.4752, -0.6122, -0.2165, -0.4626,
           0.1371,  0.1906]]], grad_fn=<StackBackward0>)



tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
       grad_fn=<SubBackward0>)


In [ ]:
for p in rnn.named_parameters():
  if 'weight' in p[0]:
    print(f'{p[0]} has size {list(p[1].shape)}')

weight_ih_l0 has size [16, 9]
weight_hh_l0 has size [16, 16]


In [ ]:
class RNNnet(nn.Module):
  def __init__(self,input_size,num_hidden,num_layers):
    super().__init__()

    self.input_size = input_size
    self.num_hidden = num_hidden
    self.num_layers = num_layers

    self.rnn = nn.RNN(input_size,num_hidden,num_layers)

    self.out = nn.Linear(num_hidden,1)

  def forward(self,x):

    print(f'Input: {list(x.shape)}')

    hidden = torch.zeros(self.num_layers,batchsize,self.num_hidden)
    print(f'Hidden: {list(hidden.shape)}')

    y,hidden = self.rnn(x,hidden)
    print(f'RNN-out: {list(y.shape)}')
    print(f'RNN-hidden: {list(hidden.shape)}')

    o = self.out(y)
    print(f'Output: {list(o.shape)}')

    return o,hidden

In [ ]:
net = RNNnet(input_size,hidden_size,num_layers)
print(net), print(' ')

for p in net.named_parameters():
  print(f'{p[0]} has size {list(p[1].shape)}')

RNNnet(
  (rnn): RNN(9, 16)
  (out): Linear(in_features=16, out_features=1, bias=True)
)
 
rnn.weight_ih_l0 has size [16, 9]
rnn.weight_hh_l0 has size [16, 16]
rnn.bias_ih_l0 has size [16]
rnn.bias_hh_l0 has size [16]
out.weight has size [1, 16]
out.bias has size [1]


In [ ]:
X = torch.rand(seqlength,batchsize,input_size)
y = torch.rand(seqlength,batchsize,1)
yHat,h = net(X)

lossfun = nn.MSELoss()
lossfun(yHat,y)

Input: [5, 2, 9]
Hidden: [1, 2, 16]
RNN-out: [5, 2, 16]
RNN-hidden: [1, 2, 16]
Output: [5, 2, 1]


tensor(0.7782, grad_fn=<MseLossBackward0>)